Sprint 4
anastasiya-erenkova/middle.messenger.praktikum.yandex pull request #4
Opened 2021-12-04 19:47 UTC by anastasiya-erenkova

2021-12-05 10:23 UTC, DmitryKhitrin requested changes
Спасибо за вашу работу, все выполнено согласно ТЗ) Но кажется в readme не хватает ссылки на проект на heroku, давайте туда ее добавим?)

2021-12-05 10:23 UTC, DmitryKhitrin commented on src/api/user-api.ts
> +	public static editProfile(data: object) {
Что такое object? Тип пишется с заглавной буквы) `Object`

2021-12-05 10:23 UTC, DmitryKhitrin commented on src/app.js
> +const PORT = process.env.PORT || 3000;
👍

2021-12-05 10:23 UTC, DmitryKhitrin commented on src/components/InfoBlock/InfoBlock.pug
> +      div(data-component='fields')
[EOF](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

https://eslint.org/docs/rules/eol-last

2021-12-05 10:23 UTC, DmitryKhitrin commented on webpack.config.js
> +	mode: "development",
Обычно принято разделять сборки на dev и prod. В дев режиме, нам обычно не нужны  сорсмапы, а в продакшене, в целях уменьшения бандла хотелось бы минифицировать свой код)

https://webpack.js.org/guides/production/

2021-12-06 15:10 UTC, anastasiya-erenkova commented on webpack.config.js
> +	mode: "development",
Взяла на заметку, но применять сейчас не стала из-за возникших ошибок

2021-12-06 15:10 UTC, anastasiya-erenkova commented on src/components/InfoBlock/InfoBlock.pug
> +      div(data-component='fields')
Поправила настройки prettier
Но не смогла настроить eslint, чтобы в pug он находил ошибку

2021-12-06 15:13 UTC, anastasiya-erenkova commented on src/api/user-api.ts
> +	public static editProfile(data: object) {
![image](https://user-images.githubusercontent.com/46963149/144867869-d0f0e2f5-739d-4d06-9845-74b42d16eec7.png)
Использовала как тип.
Не стала заменять на данном этапе, слишком много ошибок

2021-12-06 15:14 UTC, anastasiya-erenkova commented
Ссылка на heroku была, просто не стала изменять ее описание (`Deploy`)

2021-12-07 07:41 UTC, DmitryKhitrin approved these changes
Вот теперь все супер, удаче в следующем спринте, дальше только интереснее)

2021-12-17 05:14 UTC, merged